spring:
  application:
    name: musinsa

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:~/test;AUTO_SERVER=true;database_to_upper=false;MODE=MYSQL'
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    open-in-view: false

#logging:
#  level:
#    org.springframework.data.jpa: "debug"
#    org.hibernate: "debug"